stages:
  - build
  - docker-build
  - deploy

build:
  stage: build
  image: node
  script:
    - echo "Start building App"
    - yarn
    - yarn build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

deploy:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key.pem
    - chmod 400 key.pem

  script:
    - ssh -o StrictHostKeyChecking=no -i key.pem $USER_NAME@$PROD_SERVER_IP "docker login registry.gitlab.com/hoangman1108/1712585_1612094_1612149_be"
    - ssh -o StrictHostKeyChecking=no -i key.pem $USER_NAME@$PROD_SERVER_IP "export GPG_TTY=$(tty) && docker pull registry.gitlab.com/hoangman1108/1712585_1612094_1612149_be"
    - ssh -o StrictHostKeyChecking=no -i key.pem $USER_NAME@$PROD_SERVER_IP "docker stop 1712585_1612094_1612149_be || true && docker rm 1712585_1612094_1612149_be || true"
    - ssh -o StrictHostKeyChecking=no -i key.pem $USER_NAME@$PROD_SERVER_IP "docker run -p 4000:4000 -d --name 1712585_1612094_1612149_be registry.gitlab.com/hoangman1108/1712585_1612094_1612149_be"
